### ISSUE TITLE
Publishing library to the PlatformIO Registry

### ISSUE THREAD

**Issue by ivankravets** [ruiseixasm/Versatile_RotaryEncoder#1]
Hi @ruiseixasm,

Thanks for using PlatformIO! 🙏 

https://github.com/ruiseixasm/Versatile_RotaryEncoder/releases/tag/1.0.3

> PlatformIO has extreme difficulties in update libraries so this is a try to that platform pick up. Arduino IDE doesn't have this kind of problems!

Do you have any issues with PlatformIO Registry? Have you published the library to the registry with [pio package publish](https://docs.platformio.org/en/latest/core/userguide/pkg/cmd_publish.html) command?

P.S: The legacy crawler is enabled for your library. We don't recommend using it. Please manage your libraries personally using `pio package publish` command.

P.S.S: The library has been updated https://registry.platformio.org/libraries/ruiseixasm/Versatile_RotaryEncoder/versions

**Comment by ruiseixasm** [comment]
I did an update yesterday and named it 1.0.3 just to be processed by PlatformIO, and it worked. I only submit this and other library on Arduino platform. I never used the refered pio command in this or other of my libraries. It has been working fine so far.

What I did was simple to remove these extra files/folders from the git repository that for some reason PlatformIO doesn’t like:

include
lib
test
.gitattributes
Finally I also added the line .vscode to the file .gitignore.

I remember that the platform Arduino accepted the previous library versions with all the files above now removed.

**Comment by ivankravets** [comment]
> It has been working fine so far.

It works thanks to the legacy crawler on the PlatformIO side. It checks libraries for updates every 24 hours. This is the reason why you didn't see an update instantly. We highly recommend using `pio package publish` command. The new version will be published available immediately in the registry.
