### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by 43823845** [ruiseixasm/Versatile_RotaryEncoder#2]
When using this library, the SW valid CLK DT is invalid. Conflicts caused by other libraries have been eliminated. The MCU model is esp07s, and the pin used is 4clk 2DT 0 SW

**Comment by ruiseixasm** [comment]
Hi,

When selecting the 3 pins the library does this to them:
```
    pinMode(pin_clk, INPUT);
    pinMode(pin_dt, INPUT);
    pinMode(pin_sw, INPUT_PULLUP);
```

If you already set these pins as OUTPUT and need them as such then there may be problems. Also, try to test them as INPUT first to check if your board let's them to be used as such.

**Comment by 43823845** [comment]
> 你好，
> 
> 选择 3 个引脚时，库会对它们执行以下操作：
> 
> ```
>     pinMode(pin_clk, INPUT);
>     pinMode(pin_dt, INPUT);
>     pinMode(pin_sw, INPUT_PULLUP);
> ```
> 
> 如果您已经将这些引脚设置为 OUTPUT 并且需要它们，那么可能会出现问题。另外，首先尝试将它们作为输入进行测试，以检查您的电路板是否允许它们这样使用。

Thank you for your answer. I'm debugging and testing
