### ISSUE TITLE
Twice Turn Needed For Rotation Detection

### ISSUE THREAD

**Issue by Basitadam** [ruiseixasm/Versatile_RotaryEncoder#7]
Hi,
Wanted to use this simple encoder. For rotation detection, double turn needed

![image](https://github.com/user-attachments/assets/80218dbd-1a95-4bc9-8c82-b348cd0c48fc)

Made this modification to Versatile_RotartEncoder.cpp file, now single turn action is enough:

```
        // ROTARY READ
        if ((rotaryBits & 0b11) != (encoderBits & 0b11)) {

            rotaryBits = rotaryBits << 2 | (encoderBits & 0b11);

            // Bit Pairs Cyclic Sequence (CLK DT Pair Bits):
            // 1.   2.   3.   4.   5.
            // 11 | 01 | 00 | 10 | 11 for CCW
            // 11 | 10 | 00 | 01 | 11 for CW
            if (((rotaryBits & 0x3f)== 0b00001011) || ((rotaryBits & 0x3f) == 0b00110100)) 
            {
                rotary = left;
            } else if (((rotaryBits & 0x3f)== 0b00000111) || ((rotaryBits & 0x3f) == 0b00111000)) 
            {
                rotary = right;   
            } else {
                rotary = stopped;
            }

        } else {
            rotary = stopped;
        }
```

**Comment by ruiseixasm** [comment]
Hi, can you explain what do you mean by _single turn_ and _double turn_?

**Comment by Basitadam** [comment]
Kind of clicks when shaft turns. Need to feel that click twice. Looked at the clk and dt signals via scope, makes three changes like 11>01>00 or 00>10>11 with each click

**Comment by ruiseixasm** [comment]
Are you referring to the double click/press? That was just an after thought, it is a little extra not intended to do much more than that!

**Comment by Basitadam** [comment]
No. Just rotate

**Comment by ruiseixasm** [comment]
Well, for "just rotate" you get -1 for left and +1 for right, so you know the direction of it trough the `rotation` variable, like expressed in this example function:
```
void handleRotate(int8_t rotation) {
    Serial.print("#1 Rotated: ");
    if (rotation > 0)
	    Serial.println("Right");
    else
	    Serial.println("Left");
}
```
